### PR TITLE
Add all SGID attributes to matched record results

### LINKED ISSUE #26: Return matched address in results
image

### PR DESCRIPTION
**Pull request by stdavis**
Closes #26

Here are some examples of how the data looks in Pro:

Before:
image

After:
image
image

### CODE REVIEW

**Comment by steveoh** [comment]
On the surface my graphql voice says that it's sending more data than necessary. My rational voice says it's probably not an issue since it's a slow interval request. I might recommend putting the "extra" data in an attributes dictionary to match a graphic more closely but I don't know how that would appear in pro.

**Comment by stdavis** [comment]
> On the surface my graphql voice says that it's sending more data than necessary.

I had the same thought but in the end, decided that it's not that big of a deal since it will always be only a single feature.

> I might recommend putting the "extra" data in an attributes dictionary to match a graphic more closely but I don't know how that would appear in pro.

Pro expects it in the root attributes prop as it is right now. I figured out the shape of the expected response by looking at the data that their world geocoder returned (which in most instances is WAY more fields than we would be returning from Open SGID).

**Comment by stdavis** [comment]
Wait, @steveoh, did you not approve this PR yet? I may have missed that. Let me know if there are any other concerns you have.

**Comment by steveoh** [comment]
I didn't look at any code but i'm sure it's great!

**Comment by eneemann** [comment]
I didn't have anything to add, I think the additional attributes will be nice!

**Pull request merged**
